### ISSUE TITLE
double features

### ISSUE THREAD

**Issue by uliano** [AdinAck/cargo-embassy#1]
I had to add the two comments to get cargo build successfully complete.

```
[features]
# defmt = ["dep:defmt"]
defmt-rtt = ["dep:defmt-rtt"]
panic-probe = ["dep:panic-probe"]

# [features]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "dep:panic-probe",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-stm32/defmt",
]
```

**Comment by AdinAck** [comment]
What is the exact command you ran to generate this? This does not happen in CI.

**Comment by AdinAck** [comment]
Actually i see this problem now... doesn't happen when you run the binary directly, only when run via cargo. Perhaps a new version of cargo changed something... I will investigate.

**Comment by AdinAck** [comment]
Fixed.
