### ISSUE TITLE
Dependency termimad updated, cargo-embassy install fails

### ISSUE THREAD

**Issue by JZNT** [AdinAck/cargo-embassy#19]
Steps to reproduce:

Run `cargo install cargo-embassy`

Got:

> error[E0277]: the trait bound `coolor::Color: From<crokey::crossterm::style::Color>` is not satisfied
>   --> /******/.cargo/registry/src/index.crates.io-6f17d22bba15001f/termimad-0.29.4/src/compound_style.rs:81:44
>    |
> 81 |             let src: coolor::Color = (*fg).into();
>    |                                            ^^^^ the trait `From<crokey::crossterm::style::Color>` is not implemented for `coolor::Color`, which is required by `crokey::crossterm::style::Color: Into<_>`
>    |
>    = help: the following other types implement trait `From<T>`:
>              <coolor::Color as From<AnsiColor>>
>              <coolor::Color as From<coolor::Hsl>>
>              <coolor::Color as From<coolor::Rgb>>
>              <coolor::Color as From<crossterm::style::types::color::Color>>
>              <coolor::Color as From<u8>>
>    = note: required for `crokey::crossterm::style::Color` to implement `Into<coolor::Color>`
> 

etc.

The [dependency termimad](https://github.com/AdinAck/cargo-embassy/blob/cacdd4eb663d3a0a28077fd7fcd8b4c205ac6efe/Cargo.toml#L17C1-L17C9) has just been updated to revision 0.30.0 https://github.com/Canop/termimad/commit/9a557bcffe4ac978da86cee511be66c0e6bdfbd5 , which updates also its own dependency coolor.

**Comment by AdinAck** [comment]
Resolved with #20
