### ISSUE TITLE
missing chip specifications for cargo flash

### ISSUE THREAD

**Issue by uliano** [AdinAck/cargo-embassy#2]
while `cargo run --features=defmt` works out of the box, `cargo flash` requires `--chip somechip`.

I think it would be nice that the template could provide this the same way as for `cargo run` or, if it's not workable, add some hint in the `README.md`

**Comment by AdinAck** [comment]
`cargo flash` should not work, `cargo embed` is the correct command.

I should add deployment instructions to the README, thanks.
