### ISSUE TITLE
without defmt feature cargo run fails to attach

### ISSUE THREAD

**Issue by uliano** [AdinAck/cargo-embassy#3]
I'm not really sure if I get this.

```
% cargo run                                                                                                                                                                                            (python3.11)
   Compiling nucleo446 v0.1.0 (/home/uliano/rustbedded/embassy/nucleo446)
    Finished dev [optimized + debuginfo] target(s) in 0.68s
     Running `probe-rs run --chip STM32F446RETx --connect-under-reset /home/uliano/rustbedded/embassy/nucleo446/target/thumbv7em-none-eabi/debug/nucleo446`
      Erasing ✔ [00:00:00] [###########################################################################################################################################] 16.00 KiB/16.00 KiB @ 37.11 KiB/s (eta 0s )
  Programming ✔ [00:00:00] [#############################################################################################################################################] 8.00 KiB/8.00 KiB @ 25.97 KiB/s (eta 0s )    Finished in 0.761s
ERROR probe_rs::cmd::run: Failed to attach to RTT continuing... 
```

Maybe`--features=defmt` is mandatory for cargo-run, in this case I don't really get why I need to specify it everytime

**Comment by AdinAck** [comment]
It is mandatory because I have it set up such that `defmt` is *opt-in*. This way, when it is time to deploy the production firmware, the binary is smaller and faster as there is no `defmt`.

I wanted to make debug builds automatically enable the `defmt` feature, but it seems to me that is not possible. If you can think of a way to do it a PR is more than welcome!

**Comment by AdinAck** [comment]
I could make the `defmt` feature default, in other words *opt-out*. And then for production builds one would need to explicitly add the `--no-default-features` flag.

**Comment by uliano** [comment]
so, the intended use is to have defmt with `cargo run` for debugging purposes and to leave it out in production, where the correct command should be `cargo embed`. If so yes, probably it would be easier to have the opt-out.

I'm not sure to agree with this approach. I have to buy a chip with enough flash to contain the code for defmt anyway and, for the speed in production, maybe it would be enough to rise the log level.

Moreover `--no-default-features` is kind of a duplicate of `--release` specification: they would be both required or be missing together.

**Comment by AdinAck** [comment]
I suppose that's true, I'll consider removing it, *or* adding it as an init flag if you want `defmt` to be compartmentalized or not.

**Comment by uliano** [comment]
As you like this kind of machinery, and are much more skilled than me, I'd like to express what I think it would really be nice with defmt:

To have it on the SWD wire while debugging and to have it on USB or UART in release mode.

What do you think?

**Comment by AdinAck** [comment]
That would require some kind of bootloader or application plugin. Definitely out of scope for this project. But that could certainly be a project on it's own.

**Comment by AdinAck** [comment]
I have decided the best solution *for now* is to enable `defmt` by default, if someone (like me) wants to disable `defmt` for a production binary, they can with `--no-default-features`.
